---
name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Ou 'master', dependendo do seu branch padrão

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material  # Se estiver usando o tema Material for MkDocs

      - name: Build the site
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          keep_files: false  # Limpa os arquivos antigos antes de implantar
